# Generated by Django 6.0.4 on 2026-04-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_add_questionnaire_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
    ]
