# Generated by Django 6.0.4 on 2026-05-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_alter_questionnaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='survey_json_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
