/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionnairesIndexRouteImport } from './routes/questionnaires/index'
import { Route as QuestionnaireTypesIndexRouteImport } from './routes/questionnaire-types/index'
import { Route as TakeIdRouteImport } from './routes/take/$id'
import { Route as QuestionnairesNewRouteImport } from './routes/questionnaires/new'
import { Route as QuestionnaireTypesShareRouteImport } from './routes/questionnaire-types/share'
import { Route as QuestionnaireTypesNewRouteImport } from './routes/questionnaire-types/new'
import { Route as QuestionnairesIdIndexRouteImport } from './routes/questionnaires/$id/index'
import { Route as QuestionnairesIdViewRouteImport } from './routes/questionnaires/$id/view'
import { Route as QuestionnairesIdResultsRouteImport } from './routes/questionnaires/$id/results'
import { Route as QuestionnairesIdResponseIdRouteImport } from './routes/questionnaires/$id/$responseId'
import { Route as QuestionnaireTypesIdJsonRouteImport } from './routes/questionnaire-types/$id/json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIndexRoute = QuestionnairesIndexRouteImport.update({
  id: '/questionnaires/',
  path: '/questionnaires/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireTypesIndexRoute = QuestionnaireTypesIndexRouteImport.update({
  id: '/questionnaire-types/',
  path: '/questionnaire-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeIdRoute = TakeIdRouteImport.update({
  id: '/take/$id',
  path: '/take/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesNewRoute = QuestionnairesNewRouteImport.update({
  id: '/questionnaires/new',
  path: '/questionnaires/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireTypesShareRoute = QuestionnaireTypesShareRouteImport.update({
  id: '/questionnaire-types/share',
  path: '/questionnaire-types/share',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireTypesNewRoute = QuestionnaireTypesNewRouteImport.update({
  id: '/questionnaire-types/new',
  path: '/questionnaire-types/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdIndexRoute = QuestionnairesIdIndexRouteImport.update({
  id: '/questionnaires/$id/',
  path: '/questionnaires/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdViewRoute = QuestionnairesIdViewRouteImport.update({
  id: '/questionnaires/$id/view',
  path: '/questionnaires/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdResultsRoute = QuestionnairesIdResultsRouteImport.update({
  id: '/questionnaires/$id/results',
  path: '/questionnaires/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdResponseIdRoute =
  QuestionnairesIdResponseIdRouteImport.update({
    id: '/questionnaires/$id/$responseId',
    path: '/questionnaires/$id/$responseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuestionnaireTypesIdJsonRoute =
  QuestionnaireTypesIdJsonRouteImport.update({
    id: '/questionnaire-types/$id/json',
    path: '/questionnaire-types/$id/json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questionnaire-types/new': typeof QuestionnaireTypesNewRoute
  '/questionnaire-types/share': typeof QuestionnaireTypesShareRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/take/$id': typeof TakeIdRoute
  '/questionnaire-types/': typeof QuestionnaireTypesIndexRoute
  '/questionnaires/': typeof QuestionnairesIndexRoute
  '/questionnaire-types/$id/json': typeof QuestionnaireTypesIdJsonRoute
  '/questionnaires/$id/$responseId': typeof QuestionnairesIdResponseIdRoute
  '/questionnaires/$id/results': typeof QuestionnairesIdResultsRoute
  '/questionnaires/$id/view': typeof QuestionnairesIdViewRoute
  '/questionnaires/$id/': typeof QuestionnairesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questionnaire-types/new': typeof QuestionnaireTypesNewRoute
  '/questionnaire-types/share': typeof QuestionnaireTypesShareRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/take/$id': typeof TakeIdRoute
  '/questionnaire-types': typeof QuestionnaireTypesIndexRoute
  '/questionnaires': typeof QuestionnairesIndexRoute
  '/questionnaire-types/$id/json': typeof QuestionnaireTypesIdJsonRoute
  '/questionnaires/$id/$responseId': typeof QuestionnairesIdResponseIdRoute
  '/questionnaires/$id/results': typeof QuestionnairesIdResultsRoute
  '/questionnaires/$id/view': typeof QuestionnairesIdViewRoute
  '/questionnaires/$id': typeof QuestionnairesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questionnaire-types/new': typeof QuestionnaireTypesNewRoute
  '/questionnaire-types/share': typeof QuestionnaireTypesShareRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/take/$id': typeof TakeIdRoute
  '/questionnaire-types/': typeof QuestionnaireTypesIndexRoute
  '/questionnaires/': typeof QuestionnairesIndexRoute
  '/questionnaire-types/$id/json': typeof QuestionnaireTypesIdJsonRoute
  '/questionnaires/$id/$responseId': typeof QuestionnairesIdResponseIdRoute
  '/questionnaires/$id/results': typeof QuestionnairesIdResultsRoute
  '/questionnaires/$id/view': typeof QuestionnairesIdViewRoute
  '/questionnaires/$id/': typeof QuestionnairesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questionnaire-types/new'
    | '/questionnaire-types/share'
    | '/questionnaires/new'
    | '/take/$id'
    | '/questionnaire-types/'
    | '/questionnaires/'
    | '/questionnaire-types/$id/json'
    | '/questionnaires/$id/$responseId'
    | '/questionnaires/$id/results'
    | '/questionnaires/$id/view'
    | '/questionnaires/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questionnaire-types/new'
    | '/questionnaire-types/share'
    | '/questionnaires/new'
    | '/take/$id'
    | '/questionnaire-types'
    | '/questionnaires'
    | '/questionnaire-types/$id/json'
    | '/questionnaires/$id/$responseId'
    | '/questionnaires/$id/results'
    | '/questionnaires/$id/view'
    | '/questionnaires/$id'
  id:
    | '__root__'
    | '/'
    | '/questionnaire-types/new'
    | '/questionnaire-types/share'
    | '/questionnaires/new'
    | '/take/$id'
    | '/questionnaire-types/'
    | '/questionnaires/'
    | '/questionnaire-types/$id/json'
    | '/questionnaires/$id/$responseId'
    | '/questionnaires/$id/results'
    | '/questionnaires/$id/view'
    | '/questionnaires/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestionnaireTypesNewRoute: typeof QuestionnaireTypesNewRoute
  QuestionnaireTypesShareRoute: typeof QuestionnaireTypesShareRoute
  QuestionnairesNewRoute: typeof QuestionnairesNewRoute
  TakeIdRoute: typeof TakeIdRoute
  QuestionnaireTypesIndexRoute: typeof QuestionnaireTypesIndexRoute
  QuestionnairesIndexRoute: typeof QuestionnairesIndexRoute
  QuestionnaireTypesIdJsonRoute: typeof QuestionnaireTypesIdJsonRoute
  QuestionnairesIdResponseIdRoute: typeof QuestionnairesIdResponseIdRoute
  QuestionnairesIdResultsRoute: typeof QuestionnairesIdResultsRoute
  QuestionnairesIdViewRoute: typeof QuestionnairesIdViewRoute
  QuestionnairesIdIndexRoute: typeof QuestionnairesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/': {
      id: '/questionnaires/'
      path: '/questionnaires'
      fullPath: '/questionnaires/'
      preLoaderRoute: typeof QuestionnairesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-types/': {
      id: '/questionnaire-types/'
      path: '/questionnaire-types'
      fullPath: '/questionnaire-types/'
      preLoaderRoute: typeof QuestionnaireTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take/$id': {
      id: '/take/$id'
      path: '/take/$id'
      fullPath: '/take/$id'
      preLoaderRoute: typeof TakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/new': {
      id: '/questionnaires/new'
      path: '/questionnaires/new'
      fullPath: '/questionnaires/new'
      preLoaderRoute: typeof QuestionnairesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-types/share': {
      id: '/questionnaire-types/share'
      path: '/questionnaire-types/share'
      fullPath: '/questionnaire-types/share'
      preLoaderRoute: typeof QuestionnaireTypesShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-types/new': {
      id: '/questionnaire-types/new'
      path: '/questionnaire-types/new'
      fullPath: '/questionnaire-types/new'
      preLoaderRoute: typeof QuestionnaireTypesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/$id/': {
      id: '/questionnaires/$id/'
      path: '/questionnaires/$id'
      fullPath: '/questionnaires/$id/'
      preLoaderRoute: typeof QuestionnairesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/$id/view': {
      id: '/questionnaires/$id/view'
      path: '/questionnaires/$id/view'
      fullPath: '/questionnaires/$id/view'
      preLoaderRoute: typeof QuestionnairesIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/$id/results': {
      id: '/questionnaires/$id/results'
      path: '/questionnaires/$id/results'
      fullPath: '/questionnaires/$id/results'
      preLoaderRoute: typeof QuestionnairesIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/$id/$responseId': {
      id: '/questionnaires/$id/$responseId'
      path: '/questionnaires/$id/$responseId'
      fullPath: '/questionnaires/$id/$responseId'
      preLoaderRoute: typeof QuestionnairesIdResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-types/$id/json': {
      id: '/questionnaire-types/$id/json'
      path: '/questionnaire-types/$id/json'
      fullPath: '/questionnaire-types/$id/json'
      preLoaderRoute: typeof QuestionnaireTypesIdJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestionnaireTypesNewRoute: QuestionnaireTypesNewRoute,
  QuestionnaireTypesShareRoute: QuestionnaireTypesShareRoute,
  QuestionnairesNewRoute: QuestionnairesNewRoute,
  TakeIdRoute: TakeIdRoute,
  QuestionnaireTypesIndexRoute: QuestionnaireTypesIndexRoute,
  QuestionnairesIndexRoute: QuestionnairesIndexRoute,
  QuestionnaireTypesIdJsonRoute: QuestionnaireTypesIdJsonRoute,
  QuestionnairesIdResponseIdRoute: QuestionnairesIdResponseIdRoute,
  QuestionnairesIdResultsRoute: QuestionnairesIdResultsRoute,
  QuestionnairesIdViewRoute: QuestionnairesIdViewRoute,
  QuestionnairesIdIndexRoute: QuestionnairesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
