/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionnairesIndexRouteImport } from './routes/questionnaires/index'
import { Route as TakeIdRouteImport } from './routes/take/$id'
import { Route as QuestionnairesNewRouteImport } from './routes/questionnaires/new'
import { Route as QuestionnairesIdResultsRouteImport } from './routes/questionnaires/$id/results'
import { Route as QuestionnairesIdEditRouteImport } from './routes/questionnaires/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIndexRoute = QuestionnairesIndexRouteImport.update({
  id: '/questionnaires/',
  path: '/questionnaires/',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeIdRoute = TakeIdRouteImport.update({
  id: '/take/$id',
  path: '/take/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesNewRoute = QuestionnairesNewRouteImport.update({
  id: '/questionnaires/new',
  path: '/questionnaires/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdResultsRoute = QuestionnairesIdResultsRouteImport.update({
  id: '/questionnaires/$id/results',
  path: '/questionnaires/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesIdEditRoute = QuestionnairesIdEditRouteImport.update({
  id: '/questionnaires/$id/edit',
  path: '/questionnaires/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/take/$id': typeof TakeIdRoute
  '/questionnaires/': typeof QuestionnairesIndexRoute
  '/questionnaires/$id/edit': typeof QuestionnairesIdEditRoute
  '/questionnaires/$id/results': typeof QuestionnairesIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/take/$id': typeof TakeIdRoute
  '/questionnaires': typeof QuestionnairesIndexRoute
  '/questionnaires/$id/edit': typeof QuestionnairesIdEditRoute
  '/questionnaires/$id/results': typeof QuestionnairesIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questionnaires/new': typeof QuestionnairesNewRoute
  '/take/$id': typeof TakeIdRoute
  '/questionnaires/': typeof QuestionnairesIndexRoute
  '/questionnaires/$id/edit': typeof QuestionnairesIdEditRoute
  '/questionnaires/$id/results': typeof QuestionnairesIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questionnaires/new'
    | '/take/$id'
    | '/questionnaires/'
    | '/questionnaires/$id/edit'
    | '/questionnaires/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questionnaires/new'
    | '/take/$id'
    | '/questionnaires'
    | '/questionnaires/$id/edit'
    | '/questionnaires/$id/results'
  id:
    | '__root__'
    | '/'
    | '/questionnaires/new'
    | '/take/$id'
    | '/questionnaires/'
    | '/questionnaires/$id/edit'
    | '/questionnaires/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestionnairesNewRoute: typeof QuestionnairesNewRoute
  TakeIdRoute: typeof TakeIdRoute
  QuestionnairesIndexRoute: typeof QuestionnairesIndexRoute
  QuestionnairesIdEditRoute: typeof QuestionnairesIdEditRoute
  QuestionnairesIdResultsRoute: typeof QuestionnairesIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/': {
      id: '/questionnaires/'
      path: '/questionnaires'
      fullPath: '/questionnaires/'
      preLoaderRoute: typeof QuestionnairesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take/$id': {
      id: '/take/$id'
      path: '/take/$id'
      fullPath: '/take/$id'
      preLoaderRoute: typeof TakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/new': {
      id: '/questionnaires/new'
      path: '/questionnaires/new'
      fullPath: '/questionnaires/new'
      preLoaderRoute: typeof QuestionnairesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/$id/results': {
      id: '/questionnaires/$id/results'
      path: '/questionnaires/$id/results'
      fullPath: '/questionnaires/$id/results'
      preLoaderRoute: typeof QuestionnairesIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires/$id/edit': {
      id: '/questionnaires/$id/edit'
      path: '/questionnaires/$id/edit'
      fullPath: '/questionnaires/$id/edit'
      preLoaderRoute: typeof QuestionnairesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestionnairesNewRoute: QuestionnairesNewRoute,
  TakeIdRoute: TakeIdRoute,
  QuestionnairesIndexRoute: QuestionnairesIndexRoute,
  QuestionnairesIdEditRoute: QuestionnairesIdEditRoute,
  QuestionnairesIdResultsRoute: QuestionnairesIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
